"""
user_crud.py — Data-access layer for the :class:`User` document.

This module is the ONLY place in the codebase that issues MongoDB queries for
users. Everything above it (controllers, routers) works through the
:class:`UserCRUD` interface, which keeps persistence concerns isolated and makes
the storage engine swappable without touching business logic.

Layer contract:
    * Methods here persist and retrieve data. They never enforce business rules.
    * Methods here never raise :class:`fastapi.HTTPException` — mapping a
      failure to an HTTP status code is the controller's responsibility.
    * "Not found" is expressed by returning ``None``, not by raising.

Typical usage:
    >>> crud = UserCRUD()
    >>> user = await crud.get_by_email("customer@example.com")
    >>> if user is None:
    ...     user = await crud.create_user({...})
"""

from typing import Optional

from odmantic import AIOEngine

from core import logger
from core.database.database import get_engine
from core.models.user_model import User

logging = logger(__name__)


class UserCRUD:
    """
    Create/read operations for the ``users`` collection.

    The instance borrows the process-wide ODMantic engine created by
    :func:`core.database.database.get_engine`. No connection is opened here —
    the engine owns a shared connection pool that is reused across requests.

    Attributes:
        engine: Shared ODMantic engine used for all queries in this class.
    """

    def __init__(self) -> None:
        self.engine: AIOEngine = get_engine()

    async def create_user(self, user: dict) -> User:
        """
        Insert a new user document into MongoDB.

        The incoming mapping is validated against the :class:`User` model before
        it reaches the database, so missing or mistyped fields fail fast here
        rather than corrupting the collection.

        Args:
            user: Field values for the new user. Must satisfy the :class:`User`
                schema. The ``password`` value is expected to be **already
                hashed** by the caller — this method performs no hashing.

        Returns:
            The persisted :class:`User`, including the ``id`` generated by
            MongoDB during the write.

        Raises:
            pydantic.ValidationError: If ``user`` does not satisfy the
                :class:`User` schema.
            pymongo.errors.PyMongoError: If the write fails at the database
                level (connection lost, duplicate key, timeout).

        Note:
            The return value of ``engine.save()`` is returned deliberately. The
            input mapping has no ``id`` field — that value is assigned during
            the write and exists only on the returned document.
        """
        try:
            logging.info("Creating a new user in the database")
            return await self.engine.save(User(**user))
        except Exception as error:
            logging.error(f"Error creating user: {error}")
            raise

    async def get_by_email(self, email: str) -> Optional[User]:
        """
        Fetch a single user by email address.

        Used both to enforce email uniqueness during registration and to resolve
        the account during authentication.

        Args:
            email: Email address to match. The comparison is exact and
                case-sensitive.

        Returns:
            The matching :class:`User`, or ``None`` when no document matches.
            Callers decide whether a missing user is an error.

        Raises:
            pymongo.errors.PyMongoError: If the query fails at the database
                level.
        """
        try:
            logging.info("Executing UserCRUD.get_by_email function")
            user = await self.engine.find_one(User, User.email == email)
            return user
        except Exception as error:
            logging.error(f"Error in UserCRUD.get_by_email: {error}")
            raise
